# Generated by Django 5.0.1 on 2024-02-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature_Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressao_atmosferica', models.DecimalField(decimal_places=2, max_digits=7)),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condicao_tempo', models.CharField(max_length=100)),
            ],
        ),
    ]
