# Generated by Django 5.0.1 on 2024-02-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperature_Entity',
            new_name='WeatherEntity',
        ),
    ]
