# Generated by Django 5.0.1 on 2024-03-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_api', '0002_rename_temperature_entity_weatherentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherEntity',
        ),
    ]
